### ISSUE TITLE
Anti-Slavery Manuscripts' classification export and subject export

### ISSUE THREAD

**Issue by jainanchit51** [danhan52/text_recognition#1]
How can I get this data ?

**Comment by danhan52** [comment]
Hi Anchit. Unfortunately, as I said in the README, the data isn't publicly available so unless you're doing research with the Zooniverse research team, you aren't allowed to have access to it. If you're looking for another dataset that I didn't use in my analysis, the [Rimes Database](http://www.a2ialab.com/doku.php?id=rimes_database:start) would be a good place to start.
